namespace: signupapp
name: signup
svcname: signupapp-svc
env:
  HTTP_ADDR: :3000
acr:
  uri: ""
  image: signupapp
  tag: ""
  pull: Always
deployment:
  container:
    name: next.js
    port: 3000
service:
  type: LoadBalancer
  port: 80
